### ISSUE TITLE
Functional Component Usage

### ISSUE THREAD

**Issue by LeviWilliams** [mrousavy/react-native-google-nearby-messages#6]
Hey, 

Thanks for creating this package its a lifesaver. It would be super helpful if you could post examples in the documentation of usage inside of an app that utilizes functional components with hooks. Been using your example to try to build it but I think the flow is confusing to convert to without any insight. Setting the event listeners in useEffect along with the flow of checking permissions with the permissions library mentioned in the docs.

More of a documentation/example enhancement than an issue.

Thanks!

**Comment by mrousavy** [comment]
I've designed this library with a class component approach, that's why the `connect`, `publish` and `subscribe` functions are async.

I currently rewrote my App to use functional components as well, and used this setup in my current solution:

```ts
useEffect(() => {
  const connect = async () => {
    const disconnect = await connect(GOOGLE_NEARBY_API_KEY_IOS);
    const unpublish = await publish(value);
  }

  const removeListener = addOnErrorListener((k, h, m) => {
    console.log(`[NEARBY] Error - ${k}: ${m}`);
  });

  return () => {
    disconnect(); // this also unpublishes!
    removeListener();
  };
}, [  (your deps)  ]);
```

This is not really an elegant solutions, so I'm currently thinking about 2 approaches:

1. Make the Nearby API an object-oriented API: you create an Object (constructor calls connect, which doesn't have to be awaited really: [ios init](https://github.com/mrousavy/react-native-google-nearby-messages/blob/master/ios/GoogleNearbyMessages.swift#L44-L64), [android init](https://github.com/mrousavy/react-native-google-nearby-messages/blob/master/android/src/main/java/com/mrousavy/nearby/GoogleNearbyMessagesModule.kt#L44-L100)), and then use `publish` and/or `subscribe` calls. When you're done, call one `disconnect` or `close` method on the object, since there's no such thing as a deconstructor in JS
2. Make all calls synchronous, so you can directly use them in `useEffect`. As you can see in the above examples, `connect` can be a sync call. `subscribe` ([ios](https://github.com/mrousavy/react-native-google-nearby-messages/blob/master/ios/GoogleNearbyMessages.swift#L104-L140), [android](https://github.com/mrousavy/react-native-google-nearby-messages/blob/master/android/src/main/java/com/mrousavy/nearby/GoogleNearbyMessagesModule.kt#L116-L139)) can be sync on ios, on android not really, that would be a shoot and forget...

Do you have a better idea?

**Comment by LeviWilliams** [comment]
Interesting. I don't think there is any issue with the example you provided, it makes total sense. It turns into a problem when you add the permissions flow in along with any type of complexity at all. For example: check permissions, request permissions, add listeners/publishers, on change listener fetch data (or something). It quickly turns into a mess of an async function inside useEffect. My current solution is ugly and I think this library should have a bare way of doing that. Maybe some reworking of how connect works in the future with a failsafe or even just adding react-native-permissions as a dependency.

In terms of the object-oriented approach, I see where you're going and I think that sounds like a good idea, then we don't have to worry about the sync/async calls and their differences in iOS and Android. How are you thinking that would look?

**Comment by LeviWilliams** [comment]
Also I tried implementing your example but I couldn't quite get it to work. Do you see anything wrong with this?? 

```
  useEffect(() => {
    if (bluetoothReady) {
      const disconnect = async () => {
        const connectToNearby =
          Platform.OS === 'ios'
            ? await connect('mykey')
            : await connect();
        const publishNearby = await publish('sent from nearby');
        const subscribeNearby = await subscribe(
          (m) => console.log('message found', m),
          (m) => console.log('message lost', m),
        );
      };

      const removeErrorListener = addOnErrorListener(
        (kind, hasError, message) =>
          console.log(`${kind}: ${hasError} ${message}`),
      );

      return () => {
        disconnect();
        removeErrorListener();
      };
    }
  }, [bluetoothReady]);
```

**Comment by mrousavy** [comment]
the function you're calling connect/publish in won't get executed until you call it, which you only do in the "componentWillUnmount" logic. (disconnect() call).

So rename it to startNearby or something and call it before the return, and in the return you call the nearby API function "disconnect()".

**Comment by LeviWilliams** [comment]
Yes sorry for the stupid question, so far deep into this at this point I didn't see that glaring mistake hahaha. I see in your example "disconnect" is block scoped to your connect function, how then do you call disconnect in the return?

**Comment by mrousavy** [comment]
Whoops, fixed it. See my edit. The disconnect() function is from the nearby API and also unpublishes/unsubscribes. I need to call the startNearby() func tho because otherwise that just gets declared and never called.

**Comment by LeviWilliams** [comment]
Of course, this library is awesome! I'm sorry if I'm missing something glaringly obvious - there is no exported "disconnect" method from the api. I can see the connect function returns an unsubscriber function, is that what you mean?

**Comment by mrousavy** [comment]
The `connect` function does indeed return an unsubscriber which is just the `disconnect` function wrapped, but you can't really use that in your `useEffect` because the `connect` function is async... I'll gladly accept pull requests with better solutions for the API structure, or do it on my own sometimes in the next few weeks (when I'm done with my current project, which btw led to the development of this library 😉)

But are you sure the `disconnect` function is not exported? See: https://github.com/mrousavy/react-native-google-nearby-messages/blob/master/index.ts#L30-L35

**Comment by LeviWilliams** [comment]
Yep sorry TSLint problem. Those specialized hook ideas are interesting. They definitely work better than always having mounted subscribers but it does seem a little specialized I agree. I'll make my own hook too in my project and see if I have a better idea.

**Comment by mrousavy** [comment]
@LeviWilliams I've written some hooks (1.0.10 release), take a look if you're interested.

For the restructure, I'm still not sure how I wan't to achieve it, I'm thinking about making this a class component, so being object oriented, but I couldn't find any resource or documentation for react native modules on making them object oriented instead of singletons.

**Comment by LeviWilliams** [comment]
Closing this issue as hooks have been added and docs updated.
